#Quote category lists
RENE_DESCARTES:list = [
    '''I think; therefore I am.''',
    '''The reading of all good books is like conversation with the finest men of past centuries.''',
    '''If you would be a real seeker after truth, it is necessary that at least once in your life you doubt, as far as possible, all things.''',
    '''Conquer yourself rather than the world.''',
    '''Doubt is the origin of wisdom''',
    '''Common sense is the most widely shared commodity in the world, for every man is convinced that he is well supplied with it.''',
    '''Except our own thoughts, there is nothing absolutely in our power.''',
    '''It is not enough to have a good mind; the main thing is to use it well.''',
    '''To know what people really think, pay attention to what they do, rather than what they say.''',
    '''The greatest minds are capable of the greatest vices as well as of the greatest virtues.''',
    '''And thus, the actions of life often not allowing any delay, it is a truth very certain that, when it is not in our power to determine the most true opinions we ought to follow the most probable.''',
    '''Masked, I advance.''',
    '''It is only prudent never to place complete confidence in that by which we have even once been deceived.''',
    '''You just keep pushing. You just keep pushing. I made every mistake that could be made. But I just kept pushing.''',
    '''To live without philosophizing is in truth the same as keeping the eyes closed without attempting to open them.''',
    '''There is nothing more ancient than the truth.''',
    '''Divide each difficulty into as many parts as is feasible and necessary to resolve it.''',
    '''In order to improve the mind, we ought less to learn than to contemplate.''',
    '''For I found myself embarrassed with so many doubts and errors that it seemed to me that the effort to instruct myself had no effect other than the increasing discovery of my own ignorance.''',
    '''Each problem that I solved became a rule which served afterwards to solve other problems.''',
    '''At last I will devote myself sincerely and without reservation to the general demolition of my opinions.''',
    '''Let whoever can do so deceive me, he will never bring it about that I am nothing, so long as I continue to think I am something.'''
]

WILLIAM_SHAKESPEARE:list = [
    '''The fool doth think he is wise, but the wise man knows himself to be a fool.''',
    '''Be not afraid of greatness. Some are born great, some achieve greatness, and others have greatness thrust upon them.''',
    '''Doubt thou the stars are fire;\nDoubt that the sun doth move;\nDoubt truth to be a liar;\nBut never doubt I love.''',
    '''The fault, dear Brutus, is not in our stars, but in ourselves.''',
    '''Hell is empty and all the devils are here.''',
    '''There is nothing either good or bad, but thinking makes it so.''',
    '''This above all: to thine own self be true,\nAnd it must follow, as the night the day,\nThou canst not then be false to any man.''',
    '''It is not in the stars to hold our destiny but in ourselves.''',
    '''We know what we are, but not what we may be.''',
    '''All the world's a stage,\nAnd all the men and women merely players;\nThey have their exits and their entrances;\nAnd one man in his time plays many parts,\nHis acts being seven ages.''',
    '''You speak an infinite deal of nothing.''',
    '''Words are easy, like the wind; faithful friends are hard to find.''',
    '''Though she be but little, she is fierce!''',
    '''My tongue will tell the anger of my heart, or else my heart concealing it will break.''',
    '''My bounty is as boundless as the sea,\nMy love as deep; the more I give to thee,\nThe more I have, for both are infinite.''',
    '''By the pricking of my thumbs,\nSomething wicked this way comes.''',
    '''Stars, hide your fires; Let not light see my black and deep desires.''',
    '''I like this place and could willingly waste my time in it.''',
    '''Lord, what fools these mortals be!''',
    '''thus with a kiss I die''',
    '''There are more things in Heaven and Earth, Horatio, than are dreamt of in your philosophy.''',
    '''Good night, good night! parting is such sweet sorrow,\nThat I shall say good night till it be morrow.''',
    '''Double, double, toil and trouble;\nFire burn, and cauldron bubble!''',
    '''Dispute not with her: she is lunatic.''',
    '''All that glitters is not gold.''',
    '''A rose by any other name would smell as sweet.''',
]

FRANKLIN_D_ROOSEVELT:list = [
    '''The only thing we have to fear is fear itself.''',
    '''I ask you to judge me by the enemies I have made.''',
    '''When you come to the end of your rope, tie a knot and hang on.''',
    '''Courage is not the absence of fear, but rather the assessment that something else is more important than fear.''',
    '''I'm not the smartest fellow in the world, but I can sure pick smart colleagues.'''
    '''Democracy cannot succeed unless those who express their choice are prepared to choose wisely. The real safeguard of democracy, therefore, is education.''',
    '''A smooth sea never made a skilled sailor.''',
    '''If you treat people right they will treat you right ... ninety percent of the time.''',
    '''There are many ways of going forward, but only one way of standing still.''',
    '''Men are not prisoners of fate, but only prisoners of their own minds.''',
    '''Be sincere, Be brief, Be seated.''',
    '''A conservative is a man with two perfectly good legs who, however, has never learned to walk forward.''',
    '''We have always known that heedless self interest was bad morals, we now know that it is bad economics.''',
    '''Repetition does not transform a lie into a truth.''',
    '''Human kindness has never weakened the stamina or softened the fiber of a free people. A nation does not have to be cruel to be tough.''',
    '''War is young men dying and old men talking.''',
    '''Competition has been shown to be useful\nup to a certain point and no further,\nbut cooperation, which is the thing\nwe must strive for today,\nbegins where competition leaves off.''',
    '''Great power involves great responsibility''',
    '''You are only an extra in everyone else's play.'''
    '''Those who have long enjoyed such privileges as we enjoy forget in time that men have died to win them.''',
    '''A Radical is a man with both feet firmly planted--in the air.''',
    '''A Reactionary is a somnambulist walking backwards.''',
    '''A Liberal is a man who uses his legs and his hands at the behest--at the command--of his head.'''
]

STD_MISC:list = [
    '''In the beginning, God created the heavens and the earth.''',
    '''Carpe diem.''',
    '''Give me liberty, or give me death!''',
    '''To infinity and beyond!''',
    '''Ask not what your country can do for you—ask what you can do for your country.''',
    '''Float like a butterfly, sting like a bee.''',
    '''The ends justify the means.''',
    '''Do unto others as you would have them do unto you.''',
    '''If you want to go fast, go alone. If you want to go far, go together.''',
    '''Ask, and it shall be given you; seek, and you shall find.''',
    '''Eighty percent of success is showing up.''',
    '''Elementary, my dear Watson.''',
    '''Frankly, my dear, I don't give a damn.''',
    '''Genius is one percent inspiration and ninety-nine percent perspiration.''',
    '''Hell has no fury like a woman scorned.''',
    '''I have always depended on the kindness of strangers.''',
    '''I love the smell of napalm in the morning.''',
    '''If at first you don’t succeed, try, try again.''',
    '''If you are going through hell, keep going.''',
    '''If you want something said, ask a man; if you want something done, ask a woman.''',
    '''I've got a feeling we're not in Kansas anymore.''',
    '''Life is like a box of chocolates. You never know what you’re gonna get.''',
    '''May the Force be with you.''',
    '''No one can make you feel inferior without your consent.''',
    '''Not all those who wander are lost.''',
    '''Nothing is certain except for death and taxes.''',
    '''Speak softly and carry a big stick.''',
    '''I am the master of my fate, I am the captain of my soul.'''
]

ALBERT_EINSTEIN:list = [
    '''Two things are infinite: the universe and human stupidity; and I'm not sure about the universe.''',
    '''If you can't explain it to a six year old, you don't understand it yourself.''',
    '''If you want your children to be intelligent, read them fairy tales. If you want them to be more intelligent, read them more fairy tales.''',
    '''Logic will get you from A to Z; imagination will get you everywhere.''',
    '''Life is like riding a bicycle. To keep your balance, you must keep moving.''',
    '''Anyone who has never made a mistake has never tried anything new.''',
    '''I speak to everyone in the same way, whether he is the garbage man or the president of the university.''',
    '''Never memorize something that you can look up.''',
    '''When you are courting a nice girl an hour seems like a second. When you sit on a red-hot cinder a second seems like an hour. That's relativity.''',
    '''A clever person solves a problem. A wise person avoids it.''',
    '''Science without religion is lame, religion without science is blind.''',
    '''Any fool can know. The point is to understand.''',
    '''Reality is merely an illusion, albeit a very persistent one.''',
    '''If we knew what it was we were doing, it would not be called research, would it?''',
    '''The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.''',
    '''The most beautiful experience we can have is the mysterious. It is the fundamental emotion that stands at the cradle of true art and true science.''',
    '''Once you can accept the universe as matter expanding into nothing that is something, wearing stripes with plaid comes easy.''',
    '''You never fail until you stop trying.''',
    '''Great spirits have always encountered violent opposition from mediocre minds.''',
    '''The measure of intelligence is the ability to change.''',
    '''It is not that I'm so smart. But I stay with the questions much longer.''',
    '''Gravitation is not responsible for people falling in love.''',
    '''The world is a dangerous place to live, not because of the people who are evil, but because of the people who don't do anything about it.''',
    '''Creativity is intelligence having fun.''',
    '''If A is a success in life, then A equals x plus y plus z. Work is x; y is play; and z is keeping your mouth shut.''',
    '''Black holes are where God divided by zero.''',
    '''Imagination is everything. It is the preview of life's coming attractions.''',
    '''A question that sometimes drives me hazy: am I or are the others crazy?''',
    '''I must be willing to give up what I am in order to become what I will be.'''
]

JULIUS_CAESER:list = [
    '''I came, I saw, I conquered.''',
    '''In the end, it is impossible not to become what others believe you are.''',
    '''Experience is the teacher of all things.''',
    '''I love the name of honor more than I fear death.''',
    '''It is easier to find men who will volunteer to die, than to find those who are willing to endure pain with patience.''',
    '''If you must break the law, do it to seize power: in all other cases observe it.''',
    '''It is better to create than to learn! Creating is the essence of life.''',
    '''I came to Rome when it was a city of stone ... and left it a city of marble.''',
    '''Divide and Conquer.''',
    '''I love treason but hate a traitor.''',
    '''What we wish, we readily believe, and what we ourselves think, we imagine others think also.''',
    '''It is not these well-fed long-haired men that I fear, but the pale and the hungry-looking....''',
    '''In war, events of importance are the result of trivial causes.''',
    '''As a rule, men worry more about what they can’t see than about what they can.''',
    '''When the gods intend to make a man pay for his crimes, they generally allow him to enjoy moments of success and a long period of impunity, so that he may feel his reverse of fortune, when it eventually comes, all the more keenly.''',
    '''You are afraid to die; what! Are you alive now?''',
    '''Without training, they lacked knowledge.\nWithout knowledge, they lacked confidence.\nWithout confidence, they lacked victory.''',
    '''I would rather be the first man in a village, than the second man in Rome.''',
    '''Caesar's wife must be above suspicion.''',
    '''He conquers twice, who shows mercy to the conquered.'''
]

SOCRATES:list = [
    '''The only true wisdom is in knowing you know nothing.''',
    '''The unexamined life is not worth living.''',
    '''I cannot teach anybody anything. I can only make them think.''',
    '''The only good is knowledge and the only evil is ignorance.''',
    '''Strong minds discuss ideas, average minds discuss events, weak minds discuss people.''',
    '''Wonder is the beginning of wisdom.''',
    '''To find yourself, think for yourself.''',
    '''Education is the kindling of a flame, not the filling of a vessel.''',
    '''By all means marry; if you get a good wife, you’ll become happy; if you get a bad one, you’ll become a philosopher.''',
    '''He who is not contented with what he has, would not be contented with what he would like to have.''',
    '''Sometimes you put walls up not to keep people out, but to see who cares enough to break them down.''',
    '''The secret of happiness, you see, is not found in seeking more, but in developing the capacity to enjoy less.''',
    '''Death may be the greatest of all human blessings.''',
    '''Employ your time in improving yourself by other men's writings so that you shall come easily by what others have labored hard for.''',
    '''The hour of departure has arrived, and we go our separate ways, I to die, and you to live. Which of these two is better only God knows.''',
    '''Every action has its pleasures and its price.''',
    '''Prefer knowledge to wealth, for the one is transitory, the other perpetual.''',
    '''We cannot live better than in seeking to become better.''',
    '''We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.''',
    '''Beware the barrenness of a busy life.''',
    '''Thou shouldst eat to live; not live to eat.'''
]

HERACLITUS:list = [
    '''No man ever steps in the same river twice, for it's not the same river and he's not the same man.''',
    '''Time is a game played beautifully by children.''',
    '''Much learning does not teach understanding.''',
    '''Man's character is his fate.''',
    '''We are most nearly ourselves when we achieve the seriousness of the child at play.''',
    '''How can you hide from what never goes away?''',
    '''Abundance of knowledge does not teach men to be wise.''',
    '''The content of your character is your choice. Day by day, what you choose, what you think and what you do is who you become.''',
    '''The unlike is joined together, and from differences results the most beautiful harmony.''',
    '''The soul is dyed the color of its thoughts.''',
    '''Thinking is a sacred disease and sight is deceptive.''',
    '''The awake share a common world, but the asleep turn aside into private worlds.''',
    '''The road up and the road down is one and the same.''',
    '''It ever was, and is, and shall be, ever-living fire, in measures being kindled and in measures going out.''',
    '''Out of every one-hundred men, ten shouldn’t even be there, eighty are just targets, nine are the real fighters, and we are lucky to have them, for they make the battle. Ah, but the one, one is a warrior and he will bring the others back.''',
    '''All things come into being by conflict of opposites.''',
    '''Life has the name of life, but in reality it is death.''',
    '''Stupidity is doomed, therefore, to cringe at every syllable of wisdom.''',
    '''The sun is the width of a human foot.''',
    '''Eyes and ears are bad witnesses to men having barbarian souls.''',
    '''Even what those with the greatest reputation for knowing it all claim to understand and defend are but opinions.'''
]

EDWARD_BULYER_LYTTON:list = [
    '''No happiness without order, no order without authority, no authority without unity.''',
    '''A trusty companion halves the journey and doubles the courage.''',
    '''The true spirit of conversation consists in building on another man's observation, not overturning it.''',
    '''As a scientist Throckmorton knew that if he were ever to break wind in the echo chamber, he would never hear the end of it.''',
    '''Public men are often alarmed into gratitude, seldom shamed into it.''',
    '''No organised being could ever have been called into existence by other agency than by the direct intervention of a reflective mind.''',
    '''Oh, can these men love, my Clodius? Scarcely even with the senses. How rarely a Roman has a heart! He is but the mechanism of genius—he wants its bones and flesh.''',
    '''Genius does what it must, and talent does what it can.''',
    '''Can any man doubt whether it is better to be a great statesman or a common thief?''',
    '''Happiness is the end at which they aim, not as the excitement of a moment, but as the prevailing condition of the entire existence; and regard for the happiness of each other is evinced by the exquisite amenity of their manners.''',
    '''I, artist in words, dedicate, then, to you, artist whose ideas speak in marble, this well-loved work of my matured manhood.''',
    '''Have you ever remarked, that people who live the most by themselves, reflect the most upon others: and that he who lives surrounded by the million, never thinks of any but the one individual,—himself?''',
    '''In science, read, by preference, the newest works; in literature, the oldest. The classic literature is always modern.''',
    '''Laws die, but Books never.''',
    '''No path between the stranger’s home and ours should be left unclosed, or the sorrow and evil of his home may descend to ours.''',
    '''Alas! there is no fool like him who wishes for knowledge! It is only through woe that we are taught to reflect, and we gather the honey of worldly wisdom, not from flowers, but thorns.''',
    '''I soon discovered that all civility is but the mask of design.''',
    '''The pen is mightier than the sword.''',
    '''Who shall argue with the most stubborn of all bigotries, — the fanaticism of unbelief?''',
    '''It is an error to suppose that courage means courage in everything. Most people are brave only in the dangers to which they accustom themselves.'''
]

FRANCIS_BACON:list = [
    '''Some books should be tasted, some devoured, but only a few should be chewed and digested thoroughly.''',
    '''Hope is a good breakfast, but it is a bad supper.''',
    '''A wise man will make more opportunities than he finds.''',
    '''Imagination was given to man to compensate him for what he is not; a sense of humor to console him for what he is.''',
    '''Man prefers to believe what he prefers to be true.''',
    '''Age appears best in four things: old wood to burn, old wine to drink, old friends to trust and old authors to read.''',
    '''Money is a great servant but a bad master.''',
    '''The job of the artist is always to deepen the mystery.''',
    '''It is impossible to love and be wise.''',
    '''Read not to contradict and confute, nor to believe and take for granted ...but to weigh and consider.''',
    '''There are two ways of spreading light..to be the candle or the mirror that reflects it.''',
    '''If we are to achieve things never before accomplished we must employ methods never before attempted.''',
    '''The less people speak of their greatness, the more we think of it.''',
    '''Champagne for my real friends, real pain for my sham friends.''',
    '''Philosophy when superficially studied, excites doubt. When thoroughly explored, it dispels it.''',
    '''There is no comparison between that which is lost by not succeeding and that which is lost by not trying.''',
    '''Reading maketh a full man; conference a ready man; and writing an exact man.''',
    '''The root of all superstition is that men observe when a thing hits, but not when it misses.''',
    '''Truth is so hard to tell, it sometimes needs fiction to make it plausible.''',
    '''Histories make men wise; poets, witty; the mathematics, subtle; natural philosophy, deep; moral, grave; logic and rhetoric, able to contend.''',
    '''The only really interesting thing is what happens between two people in a room.''',
    '''Great boldness is seldom without some absurdity.''',
    '''Whosoever is delighted in solitude is either a wild beast or a god.''',
    '''A prudent question is one-half of wisdom.''',
    '''Money is like manure, its only good if you spread it around.''',
    '''Silence is the virtue of fools.''',
    '''He that will not apply new remedies must expect new evils; for time is the greatest innovator.''',
    '''Nature is often hidden, sometimes overcome, seldom extinguished.''',
    '''There Are But Two Tragedies in Life--One is One's Inability to attain One's Heart's Desire--The Other Is To Have It!'''
]

ANDREW_RICE:list = [
    '''I blew kids up.''',
    '''What can I say? A little bit of Treasure on my Lady.''',
    '''I feel like I AM the danger.''',
    '''You have female pockets... I forgot. I HAVE MALE POCKETS.''',
    '''Are you talking about the Gluteus Maximus or the Gluteus Minimus?''',
    '''Does he get harvested? Does he like it?''',
    '''She was moldy in the darkness.''',
    '''Your cats are alive, your babies are dead... you should stick to the cats.''',
    '''I am deaf, dumb and blind when it comes to the present. I just live solely in my head.''',
    '''I believe in regicide.''',
    '''I should come with a Trigger Warning''',
    '''You can die... I guess...''',
    '''The gendered lifestyle isn't for you.''',
    '''They have a gun... they'll go well with your baby.''',
    '''Let me commit crib-icide.''',
    '''I feel like the context-free quotes during regicide will go hard.''',
    '''They call me Lil Noodle: I'm not cooked, I'm boiled.''',
    '''I don't need therapy. I need eyeballs.''',
    '''Can you stop relying on child labor to do anything?''',
    '''Maybe Yu-Gi-Oh is the gender we made along the way.''',
    '''Gender is the heart of the cards.''',
    '''Not the Corpse Baby... like the Corpse Bride, but less romance-able.''',
    '''I'm naked without my gender.''',
    '''You played 'Gender Role'...''',
    '''Eating up gender roles like its Thanksgiving.''',
    '''I didnt even touch the bits. I touched the spaghetti.''',
    '''You're limited to one gender at a time. You can change them freely, but you can only be one.''',
    '''I will take the sufferage from you.''',
    '''How does one obtain ordered dict?''',
    '''I am the messiah and I bring you functional code.''',
    '''She can take the heat and she's not getting out of the kitchen.''',
    '''He's not Witness Protection Brother.''',
    '''We love fat shaming babies.''',
    '''Egg plant, woman.''',
    '''Do they just control the bacteria in the air or....?''',
    '''She is too strong and too independent of a woman... she WILL crush me...''',
    '''I've adopted him through marriage.''',
    '''I dont think your reflection shows your insides...''',
    '''You are human, you're not a virus.''',
    '''Yeah, my finger cat.''',
    '''A man in a speedo...''',
    '''I have to take matters into my own dead hands.''',
    '''We're taking turns with the dead hand.''',
    '''We got our 6 pack on the side, we got our 12 sardines in the can...''',
    '''We need to do some racial profiling. Lets find some women.''',
    '''It was probably Africa for the win.''',
    '''Only men can farm me.''',
    '''Are melons drugs?''',
    '''You're snorting Elmo???''',
    '''Some days, I am a blessing. Other days, I am a blight''',
    '''Boozing it in the bathroom with the asexual I summoned.''',
    '''Possum Vogue.''',
    '''You've got so much cat calling in your life.''',
    '''7 out of 10 scientists agree so...''',
    '''If you stab a person and they're bleeding out, there is more than there was before, just less alive.''',
    '''I have proof... it's in my basement.''',
    '''Oh yeah... bite my hand...''',
    '''A little bit of prayer can break the nuts.''',
    '''I have enough energy... and enough legs.''',
    '''The real Monkey is the Nuns we trafficked along the way.''',
    '''I am going to call upon Shakespeare and he will come over there and beat you.''',
    '''I speak for the Nuns... but only the Buhhdist ones that have taken a vow of silence... the rest of the nuns can speak for themselves.''',
    '''BATMAN IS A NUN??? THEY WERE SISTER NUNS??? THEN EVERYTHING CHANGED WHEN HIS PARENTS GOT THROWN DOWN A WELL???''',
    '''What if the Joker was actually a Nun gone rogue?''',
    '''If you squint hard enough and your A gets dismembered...''',
    '''Monkeys don't look like a concept of time.''',
    '''I gotta risk it for the biscuit... and my biscuits got burned.''',
    '''My baby brings all the points to the crib.''',
    '''I don't speak in errors. I only speak in success.''',
    '''I can code...''',
    '''Take me to your friend egg.''',
    '''Look how friendly he looks as he takes off his clothes?''',
    '''All the men love Janice.''',
    '''It's too large... why is it too large???''',
    '''I'm not allowed to have Janice.''',
    '''She beaned her husband in the bathroom.''',
    '''Legendary Janice licking the cup.''',
    '''We’ve milked Janice dry.''',
    '''I see small people… it must be Janice.'''
    '''I'm following Janice from Accounting.''',
    '''Oh wow... Janice cares about Syrian refugees... how inspirational!''',
    '''Where is Janice? I clicked on the link for Janice. GIVE ME JANICE!''',
    '''I don't know what my username on Twitter is... it won't let me see Janice...''',
    '''YOU KNOW WHAT? I AM GOING TO BET IT ALL ON LOVE! I'M GOING TO KILL JIM!''',
    '''I think I'm in love with Janice.''',
    '''Like when she's around my throat closes up.''',
    '''Y'all think that I like Janice? She's a married woman...''',
    '''There are a lot of fish in the sea, but all of the fish are afraid of her.''',
    '''Janice from accounting is evil.. but also she's a goddess and all of the men love her.''',
    '''I am going to kill Jim...''',
    '''When you make up a person and they're actually real... like what?''',
    '''Jim is her husband, by the way.''',
    '''You are the worst kind of girl cause you're not even bright.''',
    '''I took a step and the fields withered and died.''',
    '''I can see clearly now my eyes are gone.''',
    '''I murdered the sign and closed my eyes.''',
    '''There’s dirt and hills… it’s classic Klamath Falls.''',
    '''Did someone order muder and blasphemy?''',
    '''It's a three-way!''',
    '''I'm wordist, not numberist.''',
    '''It's like a multi-lingaulist, but less impressive.''',
    '''There are two types of cats in this world: programmers and laptops.''',
    '''That's how he chose his name while he was cosplaying a student.''',
    '''It's almost like I lost my marbles and now I am losing my mind.''',
    '''That's one of the perks of cribbage, you only need your fingers.''',
    '''Eventually the buff man let me down... he had to let me down at some point.''',
    '''I tried so hard, and I got so far... in the end, I treasured that lady.''',
    '''If only I could play the buff man.''',
    '''Buff men never let me down... they carry me.''',
    '''Grandma Tarkin: Baker of Cookies, Destroyer of Worlds.''',
    '''Have a fat man.''',
    '''The internet decided to commit chicken noodle soup-icide.''',
    '''Oh God, its so large.''',
    '''It only has 10 pp.''',
    '''Now we can punch a polar bear!''',
    '''I walked into this person's house and they started quizzing me.''',
    '''I am going to punch another frog.''',
    '''I should have committed to clubbing the seal...''',
    '''It's time to Guh Guh.''',
    '''There's a man in that rock.''',
    '''There is an ice cream pokemon that I just murdered... and now there is a goth girl that I just murdered.''',
    '''This is child labor at its finest... also, I just hatched my new child!''',
    '''I'm just hatching an egg.''',
    '''Bill Nye, the whole time.''',
    '''I know you like Racist, how do you feel about sexist?''',
    '''My weakness... dead babies...''',
    '''Oops, that's not hair.''',
    '''At least he's not racist.''',
    '''No, it's because I do drugs.''',
    '''One does not simply spill their garbage.''',
    '''In June I can summon a demon or something.''',
    '''You like normal things... I'll give you a normal one.''',
    '''Let me reset it so I can get Cecily’s Grading System in there.''',
    '''Sometimes you have to burn bridges to make lemonade.... That's how children's lemonade stands work.''',
    '''What are these men doing in my hand?''',
    '''You don't like licking your WiFi?''',
    '''ALL MY FANTASIES SHOULD COME TRUE! WHY ISNT THIS ONE?''',
    '''I don't know where my bear tax is, but my bear tax is a corpse.''',
    '''Not in my gulch''',
    '''I have 3 and a dead baby.''',
    '''It's rude to time another woman.''',
    '''I love me some sassy freeze frames.''',
    '''There isn't one, but I made one.''',
    '''It's all that food I ate.... it just started growing until it crossed timezones and it all went downhill from there.''',
    '''Oh, you know... more dead parents... not enough dead babies...''',
    '''Fortune favors the dead.''',
    '''We must illuminate the Mommy issues.''',
    '''Mamma Mia and a side of Huckleberry Pie.''',
    '''Here we got JD: the Good Ol' Fat Man... oh... now he's a fox... a very foxy man.''',
    '''All my babies are queens.''',
    '''How do you type on a keyboard?''',
    '''I had forgotten about babies... its been so long...''',
    '''She's been stockpiling the naughty cards for this moment!''',
    '''I am not cruel, but I am unusual.''',
    '''The hand is just the pic.... I need to look at the juice...''',
    '''I just need you to connect your GitHub to your Discord through some freaky AI schenanigans.''',
    '''She didn't RSVP to not exist today.''',
    '''He's just stabbing him over and over...''',
    '''How can I make my brush large-and-in-charge size?''',
    '''This is a puff puff pass.''',
    '''I like big babies and I cannot lie.''',
    '''And yet, all we get is pain and sufferage.''',
    '''I am not fluent in that breed of bad English.''',
    '''This is hideous, but it's also sexy.''',
    '''If there is a Lady Gaga, is there a Lady Googoo?''',
    '''Stupidity doesnt find me, I find it and taxidermy it on my wall.''',
    '''We got the buff man with the gangrene!''',
    '''I'm ambi-genderous.''',
    '''My premier balls.''',
    '''Cotton Eye Caps Lock.''',
    '''I can be a flesh fan.''',
    '''Just because I am stupid doesn't mean I am intelligent.''',
    '''MY QUEEN!''',
    '''I know I injested this peice of media...''',
    '''The Mafia and The Mommy Issues.''',
    '''I threw away babies.''',
    '''What? You don't like the definition of mommy issues?''',
    '''The Goron government is looking for ways to end world hunger. They have decided on cannibalism.''',
    '''Like how Jesus turned water into wine, I must turn spice into flour.''',
    '''Just say Oui Oui and you take their baguette.''',
    '''I gotta mash up the dinosaurs.... I AM THE METEOR!''',
    '''Why are there noodles everywhere?''',
    '''I am woefully unprepared for life.''',
    '''There is a clump of noodles. This feels illegal.''',
    '''You can play a buff man.''',
    '''How's my pot going?''',
    '''It's smoking hot Pikachu''',
    '''It's paralyzing me with its lick!''',
    '''Lickilicky and Gulpin: The queens.''',
    "I got an ape that is saying 'Paint me like one of your french girls.'",
    '''This is the good boy chair.''',
    '''I got the baby flush. It's potty trained!''',
    '''I don't goss, I GLAM.''',
    '''Just because I kill my babies doesnt mean that you should have one!''',
    '''I don't believe in calculators. I believe in suffering. FATHER!''',
    '''What do I do with my Meow Mix?''',
    '''What kinds of crimes are we going to commit against the fashion empire?''',
    '''You know what we do to the peasentry? ARSON!''',
    '''I love having nasal glands.''',
    '''Honey Bunches of OH NO! Now with a toy in every box!''',
    '''This lady has so many mommy issues that she became a father.''',
    '''Is it mommy issues if it's your older sister who acts as a mother figure?''',
    '''The number of people in my hand with mommy issues...''',
    '''That guy committed war crimes against China....  not to say that the God of China didn't like it...''',
    "And the other God came out of the nursery like, 'Nuh uh!'",
    '''There's a guy in my hand.''',
    '''Got 99 problems, but committing crimes against the Empire ain't one.''',
    '''They're children, exploit their weaknesses... convince them to commit crimes against the Empire!''',
    '''Commit a crime against humanity, commit two against the Empire. Love me a good deal!''',
    '''I like the idea of sitting in a pool of blood. It fits my asthetic.''',
    '''I am a bad noodle.''',
    '''I get the nibbles of the Boba Fett.''',
    '''You can't have your god being black out drunk 24/7!''',
    '''The God of Japan pulls a sword out of her boobs.''',
    '''I was stuck in Pickle hell.''',
    '''The Pickles were too powerful, so I had to stash them.''',
    '''Bill Nye, he killed a guy.''',
    '''I always go back to Germany at the end of the day to talk to the robot lady and earn my rewards.''',
    '''Shark Lady can swim on lava.''',
    '''The modern day Shark Boy and Lava Girl: Fish Lady and Dog Boy.''',
    '''OOH, Arson!''',
    '''That's a spoiled child... he's just emo.''',
    '''The shark lady is being super loud.''',
    '''Then we commit chicken noodle soup-icide.''',
    '''You fell for my tarp of dinner!''',
    '''Oh, hello there... You would have been nice if I hadn't destroyed the thing you would be nice with.''',
    '''Some games are democratic and therefore lack throwns.''',
    '''Ok class, today we address the feline gaze.''',
    '''It has been over two decades since I was git push-ed.''',
    '''Your tarp brings all the boys to the backyard.''',
    '''The mafia boss, I love her so.''',
    '''It's not a cult, it's an orphanage!''',
    '''You like Father? Lots of people like Father.''',
    '''Unholy players cannot play while judge Judy goes at it.''',
    '''I need all of the whiteness and now I need all of the blackness... we need some segregation in here.''',
    '''Yeah, gotta have something to do on a Friday night.''',
    '''Zeus' sexual appetites, you're coming with me.''',
    '''What do I do when I call upon my ancestors?''',
    '''We need a cat arsonist.''',
    '''She murdered the mother of the orphanage so she could become the father of the orphanage.''',
    '''That's the arsonist's stand-in mother.''',
    '''He makes people wet, but he also saves people from dying from the wet, so...''',
    '''Oops, all milk men... if only...''',
    '''It's raining milkmen, hallelujah.''',
    '''No Im not a player, I'm a peasantry.''',
    '''You know the arsonist I was playing?''',
    '''I want to gaze upon the arson.''',
    '''How do I generic-ify this?''',
    '''Return the Nuns... because no one expects the Nuns...''',
    '''She is a college student, so she has narcolepsy.''',
    '''My Achy Breaky Code.''',
    '''It's 'oops all Oreos,' but where is it getting the Oreos from?''',
    '''My hole is very nice.''',
    '''How many sheep is too many sheep?''',
    '''THE MELONS ARE MINE!''',
    '''Playing the racism in my hand.''',
    '''I like the part where it stings... the burning is not so great.''',
    '''How can I be a housewife without a melon fortress?''',
    '''That's child labor, and I'm here for it.''',
    '''If it's green, it's a vegetable.''',
    '''Why are you a predator to my innocent melons?''',
    '''I need to make this my wetness...''',
    '''They have to make the bats breedable.''',
    '''Hashtag: Operation... I'm out of sticks.''',
    '''I gotta be far away from those public hell goers.''',
    '''Why is he so small?! THIS IS WHY WE KILL ALL THE BABIES!''',
    '''I am the hell fortress.''',
    '''I'm going to be the perfect housewife!''',
    '''The real victory was the babies we killed along the way.''',
    '''I'm not an engineer, might as well be HR.''',
    '''I'm like the McDonald's but of clubs.''',
    '''What do I even do here? There's so many ways to have a baby...''',
    '''Takes him to the club, gets him drunk on 7 dollar wine, then he dies.''',
    '''Explode on haters.''',
    '''I am still in my math infancy.''',
    '''I will just cry in the middle of the room... just strap me to the ceiling fan...''',
    '''They're GMO sixes.''',
    '''I am actually writting code, not just sitting there looking pretty.''',
    '''It's your tarp and my funeral.''',
    '''Feeling stable, might gamble later.''',
    '''THAT'S what we call child labor.''',
    '''You're a side dish.''',
    '''You're still a father, even if it dies.''',
    '''It’s no longer spaghetti, it’s meatballs.''',
    '''I know... I am horrible and evil and... your turn.''',
    '''I close my eyes and I can see clearly now my eye lids are gone.''',
    '''Just put graduation cords in your hair and turn Nagi to stone.''',
    '''A self fulfulling tarp-rophecy''',
    '''We have open sourced software in the Cribbage Empire.''',
    '''It doesn't matter, its our baby. We're communist's here.''',
    '''Woah, that's child labor right there!''',
    '''I have secured Janice.''',
    '''Sorry, I’ve got to go put down some dead babies.''',
    '''And our special guest: Dead Baby!''',
    '''The dest is correct, the src is correct, the n is correct...''',
    '''I just hnad.''',
    '''You are infinite and I am sleep.''',
    '''That would have been a lot of child labor right there.''',
    '''His discord says he’s away. Did he just not click on Discord for a while or did he die with his computer on? Who’s to say, really...''',
    '''Same FBI bestie. But, like, if you find the cribbage server, at me and I can try over a game of cribbage.''',
    '''Janus got alphabet souped.''',
    '''Another one bites the cake.''',
    '''Sometimes ‘u’s are just ‘re’s''',
    '''I am a programmer, I’ll devour those bytes one nibble at a time.''',
    '''The baby didn’t die, but I did. The next generation lives to see another day.''',
    '''At least it was a crib and not a crypt.''',
    '''AND THE BABY IS…. a corpse? I’m such a bad parent. I’ve killed three babies today.''',
    '''When they said 6 feet for social distancing, I thought they meant 6 feet under. Sorry, baby.''',
    '''Oogity boogity bippity bop.''',
    '''Was Humpty Dumpty a crackhead?''',
    '''To raise the baby, you must first become the baby.''',
    '''I love it when things break.''',
    '''Oh my gosh, Becky, look at my wildness.''',
    '''I have dominion over the sexy babies.''',
    '''Like look at all of those sexy babies over there... Like, Tay-Tay, no, not for you...''',
    '''We gotta do some genetic engineering.''',
    '''Absence makes the heart grow massive.''',
    '''Something about those hand pics... just gives them to the wrong person... this should not be weird.''',
    '''We’re on temporary hiatus from selling hand pics.''',
    '''JUST LOOK AT THIS JANK!''',
    '''Don’t die now, baby! I love you!''',
    '''I either kill them or they love me.''',
    '''THAT'S MY BABY! HE'S POLLUTING MY BABY!''',
    '''Two points and a dead baby.''',
    '''I get the same points either way, so I might as well commit tax fraud.''',
    '''How to build a better world: One baby at a time.''',
    '''It takes a village to kill a child.''',
    '''It’s just a shelf to hold your body when you’re not using it.''',
    '''We are one big baby away from domination.''',
    '''I’m going to multithread your life.''',
    '''You’re stealing the baby!''',
    '''I have killed several babies.''',
    '''With programming, you learn to kill children.''',
    '''You have been forged on the battlefield. I AM THE BATTLEFIELD!''',
    '''Strictly less than baby.''',
    '''Andrew Rizz''',
    '''That's horrendous. Why?''',
    '''I saw Janice from accounting in the club, that two faced bitch!''',
    '''Detective Pika-Drew.''',
    '''I am bad at life and I had no choice.''',
    '''The baby is dead if you don't give it body parts.''',
    '''#include SPICE;''',
    '''So much cake, so much lady.''',
    '''Farming Andrew for Quotes in All Accents.''',
    '''Sometime the spice is in the garbage, sometimes the spice is in the treasure.''',
    '''It’s becoming a muscle soon.''',
    '''JUST BECAUSE THE BABY FLOURISHED UNDER MY CARE...''',
    '''At this point, you might as well just use vim.''',
    '''You fell for my tarp. It's ok, people usually do.''',
    '''Your traps don't concern me, mortal!''',
    '''You got the nibble.... the Jacobins are hungry. LET THEM EAT CAKE!''',
    '''The real trap was the friends that we made along the way.''',
    '''Your existance is an error.''',
    '''I like hitting people.''',
    '''I need it to be more efficient. There are no fish. The water is polluted.''',
    '''I am running out of names for these variables. I need to go to a baby book and just start naming things. Like the baby directory.''',
    '''This is me trying to be nice, but it just turned into blue. Like the ocean, but its very polluted.''',
    '''My life is out of context.''',
    '''I like this function... it's like geese in flight... it's gorgeous...''',
    '''The fat baby needs to pass these in, hold up.''',
    '''I require the weiner.''',
    '''Inject the results straight into the DMs.''',
    '''I'm blinder than a bat wearing sunglasses.''',
    '''I am going to play my last card for... the program crashing.''',
    '''Garbage Man by Day, Treasure Lady by Night.''',
    '''The garbage man recycles.''',
    '''The garbage man gives garbage hands.'''
]

CHEYENNE_STESKAL:list = [
    '''Well I make more than you…''',
    '''I bring the party. The party is racism.''',
    '''Alec you always look like your blinking.''',
    '''If only I were a man...''',
    '''You're trying to drag me down to your level, your more stupider level.''',
    '''You make your wife sleep in a separate bed near the door? WHAT KIND OF HOME ARE YOU LIVING IN???''',
    '''I can't flip the flamingos?''',
    '''Can I get this kid an egg? I dont think she liked that.''',
    '''I should make a new mayonaise machine. #FarmingProblem''',
    '''I just tried to milk a sheep. It told me that it can't produce milk... it told me itself in the third person.''',
    '''Life is really interesting when you have short term memory.''',
    '''I don’t want to live like a French Man.''',
    '''We’re excited for STIs!''',
    '''Racist against football players :sunglasses:''',
    '''I have a lot of Phil lore.''',
    '''I can transition in the wizard's basement.''',
    '''I need to befriend the wizard.''',
    '''Where is Lewis? I need to return his underpants.''',
    '''I'm torn between that and Goats Eating Cans.''',
    '''You sound like ChatGPT.''',
    '''Indegenous Canadian.''',
    '''Homeless people is always a good option.''',
    '''I was just staring at the not farmville...''',
    '''Why you talking about toilet paper?''',
    '''I’m racial profiling right now.''',
    '''My sheep tip off worked.''',
    '''That guy's white, that doesn't help.''',
    '''This class is more alcoholic than ours!''',
    '''I got the microwave and it all went downhill from there.''',
    '''No! My house is too big!''',
    '''Maybe its Maybelline, maybe its Magic the Gathering.''',
    '''You kicked me?''',
    '''I was going to buy Plant Identification.''',
    '''I'm like Texas during a winter snowstorm.''',
    '''The Snack Bar is right in my face.''',
    '''Why didn't I buy Bacon and Eggs?''',
    '''I'm going to rage quit Tabletop Simulator.''',
    '''The Kamikaze Pilots didn’t win?''',
    '''I wasted the Nissan Pathfinder on that?''',
    '''How dare you Cheyenne? You Filipino...''',
    '''I’m not the only one who gets racist cards.''',
    '''I love both.''',
    '''Hello fellow men.''',
    '''Congratulations on your 'Nazi Simp' and your 'Not Racist' Awards!''',
    '''AH! MY GENITALS!''',
    '''I can't just go with Necrophilia!''',
    '''I'd go for Tentacle Porn.''',
    '''I'd put Garcia on my list.''',
    '''Yeah, I got whiskey.''',
    '''I’m too well off in real life so I must do this to feel anything: a homeless cowboy.''',
    '''They just look like mouth-breathing Neanderthals.''',
    '''I'm just reconnecting with nature after a long day on Jira.''',
    '''If you choose the male version, it gets balls.''',
    '''It sucks too hard.''',
    '''Why are all of the dogs here mangy?''',
    '''That sounds like a Ken Davis moment.''',
    '''I can make the keg.''',
    '''He’s old. That’s what old people are supposed to do.''',
    '''This is communism. I bought a forest... I bought the wheat field...''',
    '''I guess if it's sushi it's appropriate to go Smeagol mode.''',
    '''Phil is the Kim Kardashian of the CSET department.''',
    '''Everyday I step outside and then I feel the chill of the wind across the hills. I see the homeless people in the Bottledrop parking lot. I hear the rattle of the grocery carts as the homeless people go by.''',
    '''Now... I can log in to Canvas...''',
    '''I’m a senior, I can be mean. What are they going to do? Kick me out?''',
    "I sometimes call him either 'what’s his face' or 'bitch.'",
    '''I thought they came out of a factory. I DIDNT KNOW YOU COULD MAKE THEM!''',
    '''No, I yap too much.''',
    '''You either die or live long enough to see yourself become Phil.''',
    '''I can’t even hurt myself.'''
]

ALEC_WONG:list = [
    '''Classic men: taking away women’s physical autonomy.''',
    '''I hate women... am I right gamers?''',
    '''Here's the closet book.''',
    '''Stinky Toilet Andrew forgot to flush.''',
    '''I am I practicing my worm or am I practicing my lobster?''',
    '''I'm going back to school to get my masters in MechaHitler.''',
    '''Me when I go to church and find a Nun type object.''',
    '''I am the main cause of deforestation.''',
    '''No one shoots Germans like Gaston.''',
    ''''But I do need to be racist against them.''',
    '''I could tell it was Canada by vibes.''',
    '''Congratulations on becoming a gopher.''',
    '''The CEO of wood.''',
    '''You say 'Ace' three times in the mirror and an asexual will appear behind you in the bathroom... at least you know they won't do anything to you cause they're not into that.''',
    '''I hate women.''',
    '''I have accidently cat dialed someone before.''',
    '''Scientists have proven that I am not a Monkey.''',
    '''I'm pretty sure that Monkeys are not the same as Honda Accords.''',
    '''THAT could have a Monkey in it.''',
    '''Have you ever considered Monkey?''',
    '''If you take the A and chop off the left leg.''',
    '''If only my mom was the judge for this round...''',
    '''Should I go American?''',
    '''You like a sex goblin with a carnival penis?''',
    '''The buffalo is the place the sauce originated from.''',
    '''Incest in my hand... I don't want it... I am not a fan.''',
    '''Alec did beat me.''',
    '''That is a bottom teir cat only because it is only bottom of cat.''',
    '''I don’t want to be a part of milking Janice.''',
    '''I may have been present when Janice was milked but I was not an active participant.''',
    '''You know axolotl but you don't know horse?''',
    '''Why does Drew turn every horse he sees into a Donkey?''',
    '''I want you to know there are no gay trucks in this country.''',
    '''My hand was really nice. It had a 6 and a 9 in it and you runied it.''',
    '''I snuck in while you were in the bathroom.''',
    '''I have never done anything intentionally in my life.''',
    '''Dutch Anal.''',
    '''It's a courtesy: after you carry the baby for 9 months, it's only fair that the baby carries you.''',
    '''Robin has successfully built a horse.''',
    '''I can't hear through my microphone''',
    '''Abbey, if we put our aces together, we'll have two aces kissing.''',
    '''An eight is just two threes kissing.''',
    '''I just feed my cat Legos.''',
    '''He's got the same pervert energies.''',
    '''Can I get hit by a train?''',
    '''I can't believe that Abbey would club a seal.''',
    '''I get to start pegging with my balls now!''',
    '''I just got a handful of balls!''',
    '''Lickilicky has abandoned me!''',
    '''You've got two muscular men in Speedos.''',
    '''Oh hell yeah, Lickilicky!''',
    '''The Nuns are trying to stop us from playing Cards Against Humanity''',
    '''The man of your dreams?''',
    '''I am not a lady, I am ChatGPT.''',
    '''By it, it's every baby I've come across.''',
    '''Man breaks into preschool with raw fish and eats it in front of the children.''',
    '''I typed in the JavaScript command.''',
    '''It’ll be like Lady and the Tramp, but we’re running over Nick.''',
    '''Why is the sea salty? All the fish are sweaty.''',
    '''What is far from the eyes but close to the heart? Intestines.''',
    '''What’s the context in your pants?'''
]

ABBEY_DUBOIS:list = [
    '''I got a hot dog. I have finally accomplished something with my life''',
    '''You're discovering something new about your hands every day...''',
    '''She usually doesn't sit on me.''',
    '''I peg amazing.''',
    '''Thats a man...''',
    '''I can play on myself.''',
    '''The pretzel bag is not your enemy!''',
    '''Or there’s the people who don’t care and just celebrate their mom's birthday.''',
    '''I have a life.... sort of.''',
    '''I was not 5 years old in Oregon.''',
    '''Stop eating this Gin STOP.''',
    '''Yeah his home is blown up in front of him, HELL YEAH SHADOW.''',
    '''Human tax.''',
    '''It sounds so good when you're stabbing Poseidon.''',
    '''And he sounds so good while he's doing it.''',
    '''I let it happen naturally... then I kill it.''',
    '''I grinded that Buneary so long to get a Lopunny.''',
    '''You could be a part of a shooting, a Kamikaze pilot, or doing drugs.''',
    '''The person I want...''',
    '''I am the perfect being!''',
    '''Virtualization: Machine go brr''',
    '''I have joined the dead baby society.''',
    '''JORDAN! YOU'RE A SOFTWARE ENGINEER! HOW DO YOU NOT KNOW HOW TO USE THE SCROLL ON YOUR TRACKPAD?!'''
]

MICAH_GORDON:list = [
    '''Why be special when you have stonks?''',
    '''If they lose an arm, they’re using their laptop wrong.''',
    '''Gordon Ramby.''',
    '''Reading is hard.''',
    '''Oh, you found a cougar... normally you find them in bars... not usually out in the wild.''',
    '''I like it when she plows my field.''',
    '''She said my wood was perfect.''',
    '''I am an old man.''',
    '''And that is how you get DP Sex.''',
    '''You don't need any game to bring out the racism in Cheyenne.''',
    '''I had a little too much fun on Sunday.''',
    '''My ass is black and blue.''',
    '''I was trying to be all honorable... but then I just shot him with a poison dart.''',
    '''Instagram is full of people being sad about Valentines Day. There’s a probability problem in there. It’s zero.''',
    '''You know what really creams my...''',
    '''I like at least two of these...''',
    '''Who's your daddy? JAVA!''',
    '''I’m about to make rice like a heathen.''',
    '''If you could send me a court mandated child that would be great.''',
    '''I'm so close...''',
    '''This is weed...''',
    '''You know what really injects my dependencies?''',
    '''Get off me Cheyenne.''',
    '''I'm just built different, just not in the right way.''',
    '''Hey hey I wasted the Devil on that one?!''',
    '''I thought that Dead Babies was going to get it.''',
    '''No, but you use them best.''',
    '''Oh... three dicks...''',
    '''I could get behind swamp ass.''',
    '''Put it in!''',
    '''You always pick racism.''',
    '''It was a good one! I had old lesbians!''',
    '''Damn, the jews lost to the gays and the terrorists.''',
    '''I played the erection at the wrong time...''',
    '''That better not go into context-free quotes...''',
    '''YEAH DEAD PARENTS FOR THE WIN!''',
    '''You’re a 50 cent woman now, Cheyenne.''',
    '''And that's how Cheyenne ended up on the Sex Offenders List... again...''',
    '''50 Shades of Cream.''',
    '''I like my coffee how I like my IDEs: dark mode.''',
    '''I'm dumb enough to know that I am smart enough to be right.''',
    '''I like my friendship like I like my grammars: context free.''',
    '''We don’t know for a fact. We know for an assumption.'''
]

CODERS_MISC:list = [
    '''Have you read the Twilight series?''',
    '''She’s calling! YOU MUST SERVICE HER.''',
    '''Edger Optimizer.''',
    '''I want to go to that one casino. What’s it called? Chlamydia.''',
    '''He hasn’t taken up my suggestion to go and scream in the hills so he plays Tarkov instead.''',
    '''I have spent all day managing nerds.''',
    '''Feel free to play with yourselves.''',
    '''It makes you creative and desperate.''',
    '''It makes Klamath Falls look like Hawaii.''',
    '''Is it racist to suggest falafel to a Syrian?''',
    '''So that means the workers that killed themselves were born about 20 seconds before the failover was initiated.''',
    '''I got a body sponsored by Ding Dong.''',
    '''Nothing is going to top DP Sex.''',
    '''I'm racially profiling.''',
    '''Or there’s the people in a relationship who are stressed about having to do something.''',
    '''Make it so even an accountant can read it.''',
    '''They drew the demon summoning state machine… and then I left.''',
    '''You don’t know what I did to the fork last Thursday.''',
    '''I got to go into the storage closet... it was an adventure.''',
    '''The point is not the point... the point is the poetry.''',
    '''Oh, I’m sure I know the taste in your mouth.''',
    '''Drugs are for me.''',
    '''I'm getting the bdsm degree.''',
    '''One hour is enough to shred me to pieces, huh?''',
    '''You remind me of the person I've been married to for 30 plus years... 1 hour...''',
    '''Cliffs are just taller hills.''',
    '''I can be all yours for an hour on Monday.''',
    '''A whole hour? Are you sure? And I can ask you to do anything I want?''',
    '''Woah, this sounds like an offline conversation.''',
    '''All my children want is knives.''',
    '''The sheer number of pizzas entering our world will cause our universe to implode into a hypermassive pizza black hole. This is why you can not divide your pizza by 0.''',
    '''I am about to make a mess in my panties.''',
    '''I KILLED THREE OF 'EM ON MY WAY OVER!''',
    '''I am going to make these cows do horrible things.''',
    '''She spent a lot of money to learn how to Google appropriately!''',
    '''You can change the world; I can change my socks.''',
    '''Two hours of sexual harassment training and I still have not learned how to harass you.''',
    '''You'll have Rummy by next weekend. I promise. Don't quote me on that.''',
    '''I like to drink when I drive.''',
    '''I can’t wait for this to be over so I can take my teeth out.''',
    '''Don't let phil die!''',
    '''There’re only two ways that I am going to beat my siblings: cure cancer or adopt a hungry child from Africa.''',
    '''Are you going to ask me if I care?''',
    '''I think you guys are just too frightened about having a good player for bowling.''',
    '''Micah looks like if you asked ChatGPT to generate a fireman.''',
    '''It’s not about how many you get, it’s about how cool you look.''',
    '''It spiralled in and I got lost.''',
    '''I go very cautiously... at 120.''',
    '''ChatGPT hasn’t replaced me (yet).''',
    '''In an interval, there is an infinite number of rational numbers within the interval.''',
    '''Can I borrow this table?''',
    '''If you have a lot of things plugged into a power strip, how do you stop yourself from pulling the plug on your life support? You simply don't pull the plug.''',
    '''COME ON BIG BABIES!''',
    '''I’m going to make you a single threaded process.''',
    '''I think it's an ID10T Error.''',
    '''If you call it with stupid inputs, you will get stupid behavior.''',
    '''It's like monkey bars--you don't want to let go of two bars at the same time or else you'll fall and kill yourself.''',
    '''I'm at a loss of understanding where things went wrong.''',
    '''What did I do? I didn’t do it and I am not responsible. Okay, I did it, but I am not responsible.''',
    '''It’s smack-you-with-a-dead-fish obvious!''',
    '''I didn’t break it! I made it do a barrel roll!''',
    '''Don’t stretch it too far. You don’t want to over stretch it.'''
]

ROOT:list = [
    '''Why is our friendship Ronald Mc Donald with a baseball bat?''',
    '''I have two brain cells left in my brain: Ctrl+C and Ctrl+V.''',
    '''It's just me, myself, and I.''',
    '''You're a multi-wordist.''',
    '''My spunky wizard boy Gandalf.''',
    '''She eating good.''',
    '''If you squint hard enough, it's the right flavor.''',
    '''We had cat tax, dog tax...''',
    '''Alec had to hijack the president's helicopter.''',
    '''This is the tale of how Abbey broke Pokemon.''',
    '''We need to meet our Quote-as.''',
    '''Then you'd have a really thick A.''',
    '''When in doubt: Trash.''',
    '''Dead babies and war crimes. A part of any balanced breakfast!''',
    '''You're down for waterboarding?''',
    '''Alec is killing it.''',
    '''It was all the child labor.''',
    '''It’s John Appleseed. Security code is 445... still working on his credit card number...''',
    '''You’re notorious for babies not flourishing under your care...''',
    '''You need your lucky Cheyenne’s foot.''',
    '''Do you have security clearance?''',
    '''Feel free to laugh at me. I am a walking joke.''',
    '''I have a massive package.''',
    '''Why'd you have to go make things so complicated?''',
    '''Jon killed me, and now I'm working again.'''
]

STD_QUOTES:dict = {
    "Rene Descartes" : RENE_DESCARTES,
    "William Shakespeare" : WILLIAM_SHAKESPEARE,
    "Franklin D. Roosevelt" : FRANKLIN_D_ROOSEVELT,
    "Miscellaneous" : STD_MISC,
    "Albert Einstein" : ALBERT_EINSTEIN,
    "Julius Caeser" : JULIUS_CAESER,
    "Socrates" : SOCRATES,
    "Heraclitus" : HERACLITUS,
    "Edward Bulyer-Lytton" : EDWARD_BULYER_LYTTON,
    "Francis Bacon" : FRANCIS_BACON
}

CODERS_QUOTES:dict = {
    "Andrew Rice" : ANDREW_RICE,
    "Cheyenne Steskal" : CHEYENNE_STESKAL,
    "Abbey Dubois" : ABBEY_DUBOIS,
    "Alec Wong" : ALEC_WONG,
    "Micah Gordon" : MICAH_GORDON,
    "Miscellaneous" : CODERS_MISC,
    "Root (OfTheProblem)" : ROOT
}