import Games.deck as dk

BLACK = ":flag_black:"
WHITE = ":flag_white:"

class White_Deck(dk.Deck):
	def reset_deck(self):
		self.deck = []
		self.flipped = None #Card that gets flipped after throwing cards away

		for card_text, color in WHITE_CARDS.items():\
			self.deck.append(dk.Card(card_text, color))

class Black_Deck(dk.Deck):
    def reset_deck(self):
        self.deck = []
        self.flipped = None #Card that gets flipped after throwing cards away

        for card_text, color in BLACK_CARDS.items():
            self.deck.append(dk.Card(card_text, color))
    
WHITE_CARDS = {
	"72 virgins" : 1,
	"8 oz of sweet Mexican black-tar heroin" : 1,
	"A Bop It" : 1,
	"A Gypsy curse" : 1,
	"A Super Soaker full of cat pee" : 1,
	"A bag of magic beans" : 1,
	"A balanced breakfast" : 1,
	"A beached whale" : 1,
	"A big black dick" : 1,
	"A big hoopla about nothing" : 1,
	"A bleached asshole" : 1,
	"A bloody pacifier" : 1,
	"A brain tumor" : 1,
	"A can of whoop-ass" : 1,
	"A clandestine butt scratch" : 1,
	"A cooler full of organs" : 1,
	"A crappy little hand" : 1,
	"A death ray" : 1,
	"A defective condom" : 1,
	"A disappointing birthday party" : 1,
	"A drive-by shooting" : 1,
	"A falcon with a cap on its head" : 1,
	"A fetus" : 1,
	"A foul mouth" : 1,
	"A gassy antelope" : 1,
	"A gentle caress of the inner thigh" : 1,
	"A good sniff" : 1,
	"A homoerotic volleyball montage" : 1,
	"A hot mess" : 1,
	"A lifetime of sadness" : 1,
	"A look-see" : 1,
	"A low standard of living" : 1,
	"A mating display" : 1,
	"A micro-penis" : 1,
	"A middle-aged man on roller skates" : 1,
	"A mime having a stroke" : 1,
	"A moment of silence" : 1,
	"A monkey smoking a cigar" : 1,
	"A mopey zoo lion" : 1,
	"A murder most foul" : 1,
	"A nuanced critique" : 1,
	"A passionate Latino lover" : 1,
	"A really cool hat" : 1,
	"A rival dojo" : 1,
	"A robust mongoloid" : 1,
	"A sad handjob" : 1,
	"A salty surprise" : 1,
	"A sassy black woman" : 1,
	"A sausage festival" : 1,
	"A sea of troubles" : 1,
	"A snapping turtle biting the tip of your penis" : 1,
	"A stray pube" : 1,
	"A thermonuclear detonation" : 1,
	"A time travel paradox" : 1,
	"A tiny horse" : 1,
	"A web of lies" : 1,
	"A windmill full of corpses" : 1,
	"A woman scorned" : 1,
	"A zesty breakfast burrito" : 1,
	"AIDS" : 1,
	"AXE Body Spray" : 1,
	"Aaron Burr" : 1,
	"Active listening" : 1,
	"Actually taking candy from a baby" : 1,
	"Adderall" : 1,
	"African children" : 1,
	"Agriculture" : 1,
	"Alcoholism" : 1,
	"All-you-can-eat shrimp for $4.99" : 1,
	"Altar boys" : 1,
	"American Gladiators" : 1,
	"Amputees" : 1,
	"An M. Night Shyamalan plot twist" : 1,
	"An Oedipus complex" : 1,
	"An asymmetric boob job" : 1,
	"An erection that lasts longer than four hours" : 1,
	"An honest cop with nothing left to lose" : 1,
	"An icepick lobotomy" : 1,
	"Anal beads" : 1,
	"Another goddamn vampire movie" : 1,
	"Apologizing" : 1,
	"Appreciative snapping" : 1,
	"Arnold Schwarzenegger" : 1,
	"Asians who aren't good at math" : 1,
	"Assless chaps" : 1,
	"Attitude" : 1,
	"Auschwitz" : 1,
	"Authentic Mexican cuisine" : 1,
	"Autocannibalism" : 1,
	"BATMAN!!!" : 1,
	"Balls" : 1,
	"Barack Obama" : 1,
	"Beating your wives" : 1,
	"Bees?" : 1,
	"Being a busy adult with many important things to do" : 1,
	"Being a dick to children" : 1,
	"Being a dinosaur" : 1,
	"Being a motherfucking sorcerer" : 1,
	"Being fabulous" : 1,
	"Being marginalized" : 1,
	"Being on fire" : 1,
	"Being rich" : 1,
	"Bill Nye the Science Guy" : 1,
	"Bingeing and purging" : 1,
	"Bitches" : 1,
	"Black people" : 1,
	"Bling" : 1,
	"Booby-trapping the house to foil burglars" : 1,
	"Boogers" : 1,
	"Bosnian chicken farmers" : 1,
	"Breaking out into song and dance" : 1,
	"Cards Against Humanity" : 1,
	"Carnies" : 1,
	"Catapults" : 1,
	"Centaurs" : 1,
	"Chainsaws for hands" : 1,
	"Charisma" : 1,
	"Cheating in the Special Olympics" : 1,
	"Child abuse" : 1,
	"Child beauty pageants" : 1,
	"Children on leashes" : 1,
	"Chivalry" : 1,
	"Christopher Walken" : 1,
	"Chutzpah" : 1,
	"Civilian casualties" : 1,
	"Clams" : 1,
	"Classist undertones" : 1,
	"Coat hanger abortions" : 1,
	"Cockfights" : 1,
	"College" : 1,
	"Concealing a boner" : 1,
	"Consultants" : 1,
	"Copping a feel" : 1,
	"Coughing into a vagina" : 1,
	"Count Chocula" : 1,
	"Crippling debt" : 1,
	"Crystal meth" : 1,
	"Cuddling" : 1,
	"Customer service representatives" : 1,
	"Cybernetic enhancements" : 1,
	"Daddy issues" : 1,
	"Dancing with a broom" : 1,
	"Darth Vader" : 1,
	"Date rape" : 1,
	"Dead babies" : 1,
	"Dead parents" : 1,
	"Deflowering the princess" : 1,
	"Dental dams" : 1,
	"Dick Cheney" : 1,
	"Dick fingers" : 1,
	"Doin' it in the butt" : 1,
	"Doing the right thing" : 1,
	"Domino's Oreo Dessert Pizza" : 1,
	"Dorito breath" : 1,
	"Drinking alone" : 1,
	"Dropping a chandelier on your enemies and riding the rope up" : 1,
	"Dry heaving" : 1,
	"Dwarf tossing" : 1,
	"Dying" : 1,
	"Dying of dysentery" : 1,
	"Eating all of the cookies before the AIDS bake-sale" : 1,
	"Eating an albino" : 1,
	"Eating the last known bison" : 1,
	"Edible underpants" : 1,
	"Elderly Japanese men" : 1,
	"Embryonic stem cells" : 1,
	"Emotions" : 1,
	"Enormous Scandinavian women" : 1,
	"Erectile dysfunction" : 1,
	"Estrogen" : 1,
	"Ethnic cleansing" : 1,
	"Eugenics" : 1,
	"Euphoria by Calvin Klein" : 1,
	"Exactly what you'd expect" : 1,
	"Exchanging pleasantries" : 1,
	"Expecting a burp and vomiting on the floor" : 1,
	"Explosions" : 1,
	"Fabricating statistics" : 1,
	"Famine" : 1,
	"Fancy Feast" : 1,
	"Farting and walking away" : 1,
	"Fear itself" : 1,
	"Feeding Rosie O'Donnell" : 1,
	"Fiery poops" : 1,
	"Figgy pudding" : 1,
	"Finding a skeleton" : 1,
	"Finger painting" : 1,
	"Fingering" : 1,
	"Firing a rifle into the air while balls deep in a squealing hog" : 1,
	"Five-Dollar Footlongs" : 1,
	"Flash flooding" : 1,
	"Flesh-eating bacteria" : 1,
	"Flightless birds" : 1,
	"Flying sex snakes" : 1,
	"Foreskin" : 1,
	"Forgetting the Alamo" : 1,
	"Former President George W. Bush" : 1,
	"Free samples" : 1,
	"Friction" : 1,
	"Friendly fire" : 1,
	"Friends who eat all the snacks" : 1,
	"Friends with benefits" : 1,
	"Frolicking" : 1,
	"Full frontal nudity" : 1,
	"Gandalf" : 1,
	"Gandhi" : 1,
	"Geese" : 1,
	"Genetically engineered supersoldiers" : 1,
	"Genghis Khan" : 1,
	"Genital piercings" : 1,
	"George Clooney's musk" : 1,
	"German dungeon porn" : 1,
	"Getting abducted by Peter Pan" : 1,
	"Getting drunk on mouthwash" : 1,
	"Getting in her pants, politely" : 1,
	"Getting naked and watching Nickelodeon" : 1,
	"Getting really high" : 1,
	"Getting so angry that you pop a boner" : 1,
	"Ghosts" : 1,
	"Giving 110 percent" : 1,
	"Gladiatorial combat" : 1,
	"Glenn Beck being harried by a swarm of buzzards" : 1,
	"Glenn Beck catching his scrotum on a curtain hook" : 1,
	"Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts" : 1,
	"Global warming" : 1,
	"Gloryholes" : 1,
	"GoGurt" : 1,
	"Goats eating cans" : 1,
	"Goblins" : 1,
	"God" : 1,
	"Golden showers" : 1,
	"Good grammar" : 1,
	"Grandma" : 1,
	"Grave robbing" : 1,
	"Guys who don't call" : 1,
	"Half-assed foreplay" : 1,
	"Harry Potter erotica" : 1,
	"Heartwarming orphans" : 1,
	"Her Royal Highness, Queen Elizabeth II" : 1,
	"Heteronormativity" : 1,
	"Hipsters" : 1,
	"Historical revisionism" : 1,
	"Historically black colleges" : 1,
	"Home video of Oprah sobbing into a Lean Cuisine" : 1,
	"Homeless people" : 1,
	"Hope" : 1,
	"Hormone injections" : 1,
	"Horrifying laser hair removal accidents" : 1,
	"Horse meat" : 1,
	"Hot Pockets" : 1,
	"Hot cheese" : 1,
	"Hot people" : 1,
	"Hulk Hogan" : 1,
	"Hurricane Katrina" : 1,
	"Inappropriate yodeling" : 1,
	"Incest" : 1,
	"Insatiable bloodlust" : 1,
	"Intelligent design" : 1,
	"Italians" : 1,
	"Jafar" : 1,
	"Jean-Claude Van Damme" : 1,
	"Jerking off into a pool of children's tears" : 1,
	"Jew-fros" : 1,
	"Jewish fraternities" : 1,
	"Jibber-jabber" : 1,
	"John Wilkes Booth" : 1,
	"Judge Judy" : 1,
	"Just the tip" : 1,
	"Justin Bieber" : 1,
	"Kamikaze pilots" : 1,
	"Kanye West" : 1,
	"Keanu Reeves" : 1,
	"Keg stands" : 1,
	"Kids with ass cancer" : 1,
	"Kim Jong-il" : 1,
	"Lactation" : 1,
	"Lady Gaga" : 1,
	"Lance Armstrong's missing testicle" : 1,
	"Land mines" : 1,
	"Laying an egg" : 1,
	"Leaving an awkward voicemail" : 1,
	"Leprosy" : 1,
	"Leveling up" : 1,
	"Licking things to claim them as your own" : 1,
	"Linsday Lohan at 55" : 1,
	"Literally eating shit" : 1,
	"Lockjaw" : 1,
	"Loose lips" : 1,
	"Lumberjack fantasies" : 1,
	"Lunchables" : 1,
	"Mad hacky-sack skills" : 1,
	"Making a pouty face" : 1,
	"Making the penises kiss" : 1,
	"Man meat" : 1,
	"Masturbation" : 1,
	"Mathletes" : 1,
	"Me time" : 1,
	"MechaHitler" : 1,
	"Media coverage" : 1,
	"Medieval Times Dinner and Tournament" : 1,
	"Men" : 1,
	"Menstruation" : 1,
	"Michael Jackson" : 1,
	"Michelle Obama's arms" : 1,
	"Moral ambiguity" : 1,
	"Morgan Freeman's voice" : 1,
	"Mouth herpes" : 1,
	"Mr. Clean, right behind you" : 1,
	"Muhammad (Praise Be Unto Him)" : 1,
	"Multiple stab wounds" : 1,
	"Mutually-assured destruction" : 1,
	"My collection of high-tech sex toys" : 1,
	"My genitals" : 1,
	"My humps" : 1,
	"My inner demons" : 1,
	"My machete" : 1,
	"My relationship status" : 1,
	"My sex life" : 1,
	"My soul" : 1,
	"My vagina" : 1,
	"Natalie Portman" : 1,
	"Natural male enhancement" : 1,
	"Natural selection" : 1,
	"Nazis" : 1,
	"Necrophilia" : 1,
	"Neil Patrick Harris" : 1,
	"New Age music" : 1,
	"Nickelback" : 1,
	"Nicolas Cage" : 1,
	"Nipple blades" : 1,
	"Nocturnal emissions" : 1,
	"Not giving a shit about the Third World" : 1,
	"Not reciprocating oral sex" : 1,
	"Nubile slave boys" : 1,
	"Obesity" : 1,
	"Object permanence" : 1,
	"Old-people smell" : 1,
	"Ominous background music" : 1,
	"One thousand Slim Jims" : 1,
	"Oompa-Loompas" : 1,
	"Opposable thumbs" : 1,
	"Overcompensation" : 1,
	"Overpowering your father" : 1,
	"Oversized lollipops" : 1,
	"Pabst Blue Ribbon" : 1,
	"Pac-Man uncontrollably guzzling cum" : 1,
	"Panda sex" : 1,
	"Panty raids" : 1,
	"Parting the Red Sea" : 1,
	"Party Poopers" : 1,
	"Passable transvestites" : 1,
	"Passing a kidney stone" : 1,
	"Passive-aggressive Post-it notes" : 1,
	"Pedophiles" : 1,
	"Peeing a little bit" : 1,
	"Penis envy" : 1,
	"Picking up girls at the abortion clinic" : 1,
	"Pictures of boobs" : 1,
	"Pistol-whipping a hostage" : 1,
	"Pixelated bukkake" : 1,
	"Police brutality" : 1,
	"Pooping back and forth. Forever." : 1,
	"Poor life choices" : 1,
	"Poor people" : 1,
	"Poorly-timed Holocaust jokes" : 1,
	"Porn stars" : 1,
	"Powerful thighs" : 1,
	"Prancing" : 1,
	"Praying the gay away" : 1,
	"Preteens" : 1,
	"Pretending to care" : 1,
	"Pterodactyl eggs" : 1,
	"Puberty" : 1,
	"Public ridicule" : 1,
	"Pulling out" : 1,
	"Puppies!" : 1,
	"Queefing" : 1,
	"Quiche" : 1,
	"Quivering jowls" : 1,
	"Racially-biased SAT questions" : 1,
	"Racism" : 1,
	"Raping and pillaging" : 1,
	"Raptor attacks" : 1,
	"Re-gifting" : 1,
	"Repression" : 1,
	"Republicans" : 1,
	"Revenge fucking" : 1,
	"Riding off into the sunset" : 1,
	"Ripping into a man's chest and pulling out his still-beating heart" : 1,
	"Road head" : 1,
	"Robert Downey, Jr" : 1,
	"RoboCop" : 1,
	"Ronald Reagan" : 1,
	"Roofies" : 1,
	"Ryan Gosling riding in on a white horse" : 1,
	"Same-sex ice dancing" : 1,
	"Santa Claus" : 1,
	"Sarah Palin" : 1,
	"Saxophone solos" : 1,
	"Scalping" : 1,
	"Science" : 1,
	"Scientology" : 1,
	"Scrotum tickling" : 1,
	"Scrubbing under the folds" : 1,
	"Sean Connery" : 1,
	"Sean Penn" : 1,
	"Seduction" : 1,
	"Self-loathing" : 1,
	"Seppuku" : 1,
	"Serfdom" : 1,
	"Sexting" : 1,
	"Sexual humiliation" : 1,
	"Sexual tension" : 1,
	"Sexy Siamese twins" : 1,
	"Sexy pillow fights" : 1,
	"Shaft" : 1,
	"Shapeshifters" : 1,
	"Shaquille O'Neal's acting career" : 1,
	"Sharing needles" : 1,
	"Skeletor" : 1,
	"Slow motion" : 1,
	"Smallpox blankets" : 1,
	"Smegma" : 1,
	"Sniffing glue" : 1,
	"Soiling oneself" : 1,
	"Soup that is too hot" : 1,
	"Space muffins" : 1,
	"Spectacular abs" : 1,
	"Sperm whales" : 1,
	"Spontaneous human combustion" : 1,
	"Statistically validated stereotypes" : 1,
	"Stephen Hawking talking dirty" : 1,
	"Stifling a giggle at the mention of Hutus and Tutsis" : 1,
	"Stranger danger" : 1,
	"Sudden Poop Explosion Disease" : 1,
	"Suicidal thoughts" : 1,
	"Sunshine and rainbows" : 1,
	"Surprise Butt-Sex!" : 1,
	"Sweet, sweet vengeance" : 1,
	"Switching to Geico" : 1,
	"Swooping" : 1,
	"Take-backsies" : 1,
	"Taking off your shirt" : 1,
	"Tangled Slinkys" : 1,
	"Tasteful side-boob" : 1,
	"Teaching a robot to love" : 1,
	"Team-building exercises" : 1,
	"Teenage pregnancy" : 1,
	"Tentacle porn" : 1,
	"Testicular torsion" : 1,
	"That thing that electrocutes your abs" : 1,
	"The American Dream" : 1,
	"The Amish" : 1,
	"The Big Bang" : 1,
	"The Blood of Christ" : 1,
	"The Care Bear Stare" : 1,
	"The Chinese gymnastics team" : 1,
	"The Dance of the Sugar Plum Fairy" : 1,
	"The Donald Trump Seal of Approval" : 1,
	"The Fanta girls" : 1,
	"The Force" : 1,
	"The Gulags" : 1,
	"The Hamburglar" : 1,
	"The Holy Bible" : 1,
	"The Hustle" : 1,
	"The Jews" : 1,
	"The KKK" : 1,
	"The Kool-Aid Man" : 1,
	"The Little Engine That Could" : 1,
	"The Make-A-Wish Foundation" : 1,
	"The Pope" : 1,
	"The Rapture" : 1,
	"The Rev. Dr. Martin Luther King, Jr." : 1,
	"The South" : 1,
	"The Tempur-Pedic Swedish Sleep System" : 1,
	"The Three-Fifths compromise" : 1,
	"The Trail of Tears" : 1,
	"The Underground Railroad" : 1,
	"The Virginia Tech Massacre" : 1,
	"The World of Warcraft" : 1,
	"The boners of the elderly" : 1,
	"The chronic" : 1,
	"The clitoris" : 1,
	"The economy" : 1,
	"The folly of man" : 1,
	"The forbidden fruit" : 1,
	"The four arms of Vishnu" : 1,
	"The gays" : 1,
	"The glass ceiling" : 1,
	"The hardworking Mexican" : 1,
	"The harsh light of day" : 1,
	"The heart of a child" : 1,
	"The hiccups" : 1,
	"The homosexual agenda" : 1,
	"The inevitable heat death of the universe" : 1,
	"The invisible hand" : 1,
	"The milk man" : 1,
	"The miracle of childbirth" : 1,
	"The placenta" : 1,
	"The profoundly handicapped" : 1,
	"The shambling corpse of Larry King" : 1,
	"The taint; the grundle; the fleshy fun-bridge" : 1,
	"The terrorists" : 1,
	"The token minority" : 1,
	"The true meaning of Christmas" : 1,
	"The violation of our most basic human rights" : 1,
	"The Übermensch" : 1,
	"Third base" : 1,
	"Tom Cruise" : 1,
	"Toni Morrison's vagina" : 1,
	"Too much hair gel" : 1,
	"Tripping balls" : 1,
	"Tweeting" : 1,
	"Two midgets shitting into a bucket" : 1,
	"Unfathomable stupidity" : 1,
	"Uppercuts" : 1,
	"Vehicular manslaughter" : 1,
	"Viagra" : 1,
	"Vigilante justice" : 1,
	"Vigorous jazz hands" : 1,
	"Vikings" : 1,
	"Waiting 'til marriage" : 1,
	"Waking up halfnaked in a Denny's parking lot" : 1,
	"Waterboarding" : 1,
	"Wearing underwear inside-out to avoid doing laundry" : 1,
	"When you fart and a little bit comes out" : 1,
	"Whipping it out" : 1,
	"White people" : 1,
	"White privilege" : 1,
	"Wifely duties" : 1,
	"William Shatner" : 1,
	"Winking at old people" : 1,
	"Wiping her butt" : 1,
	"Women in yogurt commercials" : 1,
	"Women's suffrage" : 1,
	"Words, words, words" : 1,
	"World peace" : 1,
	"YOU MUST CONSTRUCT ADDITIONAL PYLONS" : 1,
	"Yeast" : 1,
	"Zeus's sexual appetites" : 1,

    #Custom
    "Phil's gauntlet": 1
}

BLACK_CARDS = {
    "A romantic, candlelit dinner would be incomplete without _____." : 1,
	"After Hurricane Katrina, Sean Penn brought _____ to the people of New Orleans." : 1,
	"After the earthquake, Sean Penn brought _____ to the people of Haiti." : 1,
	"Alternative medicine is now embracing the curative powers of _____." : 1,
	"And I would have gotten away with it, too, if it hadn't been for _____." : 1,
#	"And the Academy Award for _____ goes to _____." : 2,
	"Anthropologists have recently discovered a primitive tribe that worships _____." : 1,
	"BILLY MAYS HERE FOR _____!" : 1,
	"Betcha can't have just one!" : 1,
	"But before I kill you, Mr. Bond, I must show you _____." : 1,
	"Coming to Broadway this season, _____: The Musical." : 1,
	"Dear Abby, I'm having some trouble with _____ and would like your advice." : 1,
	"Due to a PR fiasco, Walmart no longer offers _____." : 1,
	"During Picasso's often-overlooked Brown Period, he produced hundreds of paintings of _____." : 1,
	"During sex, I like to think about _____." : 1,
#	"For my next trick, I will pull _____ out of _____." : 2,
	"He who controls _____ controls the world." : 1,
	"How am I maintaining my relationship status?" : 1,
	"I do not know with what weapons World War III will be fought, but World War IV will be fought with _____." : 1,
	"I drink to forget _____." : 1,
	"I got 99 problems but _____ ain't one." : 1,
	"I learned the hard way that you can't cheer up a grieving friend with _____." : 1,
#	"I never truly understood _____ until I encountered _____." : 2,
	"I wish I hadn't lost the instruction manual for _____." : 1,
	"I'm sorry, Professor, but I couldn't complete my homework because of _____." : 1,
	"In 1,000 years, when paper money is but a distant memory, _____ will be our currency." : 1,
	"In L.A. County Jail, word is you can trade 200 cigarettes for _____." : 1,
#	"In M. Night Shyamalan's new movie, Bruce Willis discovers that _____ had really been _____ all along." : 2,
	"In Michael Jackson's final moments, he thought about _____." : 1,
	"In Rome, there are whisperings that the Vatican has a secret room devoted to _____." : 1,
#	"In a world ravaged by _____, our only solace is _____." : 2,
	"In an attempt to reach a wider audience, the Smithsonian Museum of Natural History has opened an interactive exhibit on _____." : 1,
	"In his new selfproduced album, Kanye West raps over the sounds of _____." : 1,
#	"In his new summer comedy, Rob Schneider is _____ trapped in the body of _____." : 2,
	"In its new tourism campaign, Detroit proudly proclaims that it has finally eliminated _____." : 1,
	"In the distant future, historians will agree that _____ marked the beginning of America's decline." : 1,
	"In the new Disney Channel Original Movie, Hannah Montana struggles with _____ for the first time." : 1,
	"Instead of coal, Santa now gives the bad children _____." : 1,
	"It's a pity that kids these days are all getting involved with _____." : 1,
	"It's a trap!" : 1,
	"Life for American Indians was forever changed when the White Man introduced them to _____." : 1,
	"Life was difficult for cavemen before _____." : 1,
#	"Lifetime presents _____, the story of _____." : 2,
	"MTV's new reality show features eight washed-up celebrities living with _____." : 1,
	"Major League Baseball has banned _____ for giving players an unfair advantage." : 1,
	"Maybe she's born with it. Maybe it's _____." : 1,
	"Next from J.K. Rowling: Harry Potter and the Chamber of _____." : 1,
	"Next on ESPN2: The World Series of _____." : 1,
#	"Rumor has it that Vladimir Putin's favorite dish is _____ stuffed with _____." : 2,
	"Science will never explain the origin of _____." : 1,
	"Sorry everyone, I just _____." : 1,
	"Studies show that lab rats navigate mazes 50% faster after being exposed to _____." : 1,
	"TSA guidelines now prohibit _____ on airplanes." : 1,
#	"That's right, I killed _____. How, you ask? _____." : 2,
	"The CIA now interrogates enemy agents by repeatedly subjecting them to _____." : 1,
	"The U.S. has begun airdropping _____ to the children of Afghanistan." : 1,
	"The class field trip was completely ruined by _____." : 1,
	"The socialist governments of Scandinavia have declared that access to _____ is a basic human right." : 1,
	"This is the way the world ends. Not with a bang but with _____." : 1,
	"This season on Man vs. Wild, Bear Grylls must survive in the depths of the Amazon with only _____ and his wits." : 1,
	"War! What is it good for?" : 1,
	"What am I giving up for Lent?" : 1,
	"What are my parents hiding from me?" : 1,
	"What brought the orgy to a grinding halt?" : 1,
	"What did I bring back from Mexico?" : 1,
	"What did Vin Diesel eat for dinner?" : 1,
	"What did the US airdrop to the children of Afghanistan?" : 1,
	"What do old people smell like?" : 1,
	"What does Dick Cheney prefer?" : 1,
	"What don't you want to find in your Chinese food?" : 1,
	"What ended my last relationship?" : 1,
	"What gets better with age?" : 1,
	"What gives me uncontrollable gas?" : 1,
	"What has been making life difficult at the nudist colony?" : 1,
	"What helps Obama unwind?" : 1,
	"What is Batman's guilty pleasure?" : 1,
	"What never fails to liven up the party?" : 1,
	"What will I bring back in time to convince people that I am a powerful wizard?" : 1,
	"What will always get you laid?" : 1,
	"What would grandma find disturbing, yet oddly charming?" : 1,
	"What's Teach for America using to inspire inner city students to succeed?" : 1,
	"What's a girl's best friend?" : 1,
	"What's my antidrug?" : 1,
	"What's my secret power?" : 1,
	"What's that smell?" : 1,
	"What's that sound?" : 1,
	"What's the crustiest?" : 1,
	"What's the gift that keeps on giving?" : 1,
	"What's the most emo?" : 1,
	"What's the new fad diet?" : 1,
	"What's the next Happy Meal toy?" : 1,
	"What's the next superhero/sidekick duo?" : 1,
	"What's there a ton of in heaven?" : 1,
	"When I am President of the United States, I will create the Department of _____." : 1,
	"When I am a billionaire, I shall erect a 50-foot statue to commemorate _____." : 1,
	"When I pooped, what came out of my butt?" : 1,
#	"When I was tripping on acid, _____ turned into _____." : 2,
	"When I'm in prison, I'll have _____ smuggled in." : 1,
	"When Pharaoh remained unmoved, Moses called down a Plague of _____." : 1,
	"When all else fails, I can always masturbate to _____." : 1,
	"While the United States raced the Soviet Union to the moon, the Mexican government funneled millions of pesos into research on _____." : 1,
	"White people like _____." : 1,
	"Who stole the cookies from the cookie jar?" : 1,
	"Why am I sticky?" : 1,
	"Why can't I sleep at night?" : 1,
	"Why do I hurt all over?" : 1,
#	"_____ is a slippery slope that leads to _____." : 2,
	"_____. Betcha can't have just one!" : 1,
	"_____. High five, bro." : 1,
	"_____. It's a trap!" : 1,
	"_____. That's how I want to die." : 1,
	"_____: Good to the last drop." : 1,
	"_____: Kid-tested, mother-approved." : 1,
	"_____? There's an app for that." : 1,

    #Custom
    "I wouldn't have struggled in Phil's gauntlet if I'd had _____." : 1
}

# #This is how I yoinked the cards :)
# #STR was a string holding each card's text separated by newlines
# with open("cards.txt", 'w') as file:
#     for card_text in STR.split("\n"):
#         if len(card_text) > 0:
#             file.write(f'''\t"{card_text}" : 1,\n''')